#!/bin/bash
SKIP(){
git branch gh-pages
# Might need to do this first: git branch -D gh-pages
git push -u origin gh-pages # Push the new branch back to github
}
#Go to
cygstart http://urbanjost.github.io/fortran-intrinsics-manpages
